config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :authors
  resources :posts do
    collection do
      get 'homepage' # definindo a rota da homepage
      post 'homepage'
    end
  end

  root 'posts#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :subject, :text

  belongs_to :author
  belongs_to :category

  scope :recents, -> {where('created_at > ?', (Time.now.beginning_of_day - 29.days))}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :homepage
  load_and_authorize_resource except: :homepage

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  def homepage
    #@posts = Post.order('created_at desc')
    @posts = Post.recents.order('created_at desc')

    # filtragem por categoria
    @posts = @posts.where(category_id: params[:category_id]) unless params[:category_id].blank?
    # uso do unless params[:category_id].blank? para exibir somente se não for vazio

    ## fazer o busca por termos
    @posts = @posts.where('UPPER(text) LIKE ?', "%#{params[:term].upcase}%") unless params[:term].blank?
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post criado com successo.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post atualizado com successo.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post apagado com successo.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author_id, :category_id, :subject, :text)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def splitDescription(text)
    text[0..400] + "..."
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :author_id %>
    <%= form.select :author_id, Author.all.collect { | author| [author.name, author.id]}, {},  class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.select :category_id, Category.all.collect { | category| [category.description, category.id]}, {},  class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title,  class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :subject %>
    <%= form.text_field :subject,  class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :text %>
    <%= form.text_area :text,  class: 'form-control', rows: 10 %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-sucess' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Mostrar', @post %> |
<%= link_to 'Voltar', posts_path %>

app/views/posts/homepage.html.erb
<h1>Homepage</h1>
<div class="row">
 <div class="col-xs-8">
<% @posts.each do |post| %>
  <h2>Title: <%= post.title %></h2>
  <h3>Subject: <%= post.subject %></h3>
  <h4>Text: <%= splitDescription post.text %></h4>
     <%= image_tag post.author.photo.thumb.url unless post.author.photo.file.nil? %>
  <strong><%= post.author.name %></strong>
  <small><%= post.created_at %></small>
  <hr/>
<% end %>
 </div>
  <div class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">Categories</div>
      <div class="panel-body">
        <ul>
          <% Category.all.each do |category| %>
            <li><%= link_to category.description, homepage_posts_path(category_id: category.id) %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">Search</div>
      <div class="panel-body">
        <%= form_tag('/posts/homepage', method: 'post') do %>
          <%= text_field_tag(:term) %>
          <%= submit_tag('Search') %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>
<table class="table">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Assunto</th>
      <th>Texto</th>
      <th>Autor</th>
      <th>Categoria</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.subject %></td>
        <td><%= post.text %></td>
        <td><%= post.author.name %></td>
        <td><%= post.category.description unless post.category.nil? %></td>
        <td><%= link_to 'Mostrar', post %></td>
        <td><%= link_to 'Editar', edit_post_path(post) %></td>
        <td><%= link_to 'Apagar', post, method: :delete, data: { confirm: 'Deseja apagar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Post', new_post_path %>

app/views/posts/new.html.erb
<h1>Novo Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Voltar', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Titulo:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Assunto:</strong>
  <%= @post.subject %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @post.text %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @post.author.name %>
</p>

<%= link_to 'Editar', edit_post_path(@post) %> |
<%= link_to 'Voltar', posts_path %>